apiVersion: v1
kind: Secret
metadata:
  name: ${DB_NAME}-secret
  namespace: ${NAMESPACE}
type: Opaque
data:
  ${ENV_USERNAME_VAR}: $(echo -n "${DB_USERNAME}" | base64)
  ${ENV_PASSWORD_VAR}: $(echo -n "${DB_PASSWORD}" | base64)
  ${ENV_DB_VAR}: $(echo -n "${DB_NAME}" | base64)