---
- name: Deploy Database to Kubernetes Cluster
  hosts: k8s_master
  become: yes
  vars:
    cloudinator_dir: /home/sen/cloudinator
    db_name: "{{ db_name }}"
    db_type: "{{ db_type }}"
    db_version: "{{ db_version }}"
    namespace: "{{ namespace }}"
    db_password: "{{ db_password }}"
    db_username: "{{ db_username }}"
    domain_name: "{{ domain_name }}"
    storage_size: "{{ storage_size }}"
    port: "{{ port }}"

  tasks:
    - name: Ensure cloudinator directory exists
      file:
        path: "{{ cloudinator_dir }}"
        state: directory
        mode: '0755'

    - name: Create required subdirectories
      file:
        path: "{{ cloudinator_dir }}/{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - scripts/database
        - templates

    - name: Copy deployment scripts and templates
      copy:
        src: "{{ item.src }}"
        dest: "{{ cloudinator_dir }}/{{ item.dest }}"
        mode: '0755'
      with_items:
        - { src: '../deploy-database.sh', dest: 'deploy-database.sh' }
        - { src: '../scripts/database/', dest: 'scripts/database/' }
        - { src: '../templates/', dest: 'templates/' }

    - name: Execute database deployment script
      command: >
        bash {{ cloudinator_dir }}/deploy-database.sh
        {{ db_name }}
        {{ db_type }}
        {{ db_version }}
        {{ namespace }}
        {{ db_password }}
        {{ db_username }}
        {{ domain_name }}
        {{ storage_size }}
        {{ port }}
      register: deploy_output

    - name: Display deployment output
      debug:
        var: deploy_output.stdout_lines